"""
Hermes Smart Router — Railway entrypoint.

Bootstraps the Hermes gateway with our Smart Router shimmed into the
per-turn model resolution hook.

Boot sequence:
    1. Ensure HERMES_HOME directory exists (Railway volume = /data).
    2. Seed a minimal config.yaml if absent (model + OpenRouter provider).
    3. Install the Smart Router shim over agent.smart_model_routing.resolve_turn_route.
    4. Run gateway.run.start_gateway.

Run with:
    python -m custom.entry
"""
from __future__ import annotations

import asyncio
import logging
import os
import sys
from pathlib import Path


def _setup_logging() -> None:
    level = os.environ.get("LOG_LEVEL", "INFO").upper()
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )


def _ensure_hermes_home() -> Path:
    """Ensure HERMES_HOME exists and is writable. Default to /data on Railway."""
    hermes_home = os.environ.get("HERMES_HOME")
    if not hermes_home:
        if Path("/data").is_dir():
            hermes_home = "/data"
        else:
            hermes_home = str(Path.home() / ".hermes")
        os.environ["HERMES_HOME"] = hermes_home

    home_path = Path(hermes_home)
    home_path.mkdir(parents=True, exist_ok=True)
    logging.info("HERMES_HOME = %s", home_path)
    return home_path


_CONFIG_TEMPLATE = """\
# Auto-generated by custom/entry.py on first boot.
# The Smart Router shim overrides per-turn routing, so model/provider here
# only serve as the fallback "primary" when the shim is bypassed.

model:
  default: "openai/gpt-5.4-nano"
  provider: "openrouter"
  base_url: "https://openrouter.ai/api/v1"

# Disable Hermes's built-in smart routing — our shim replaces it entirely.
smart_model_routing:
  enabled: false

agent:
  # Shorten gateway timeout to avoid Railway worker lockup on stuck agents.
  gateway_timeout: 900
  gateway_timeout_warning: 600
  gateway_notify_interval: 300
"""


def _seed_config_if_missing(home_path: Path) -> Path:
    """Write a minimal config.yaml if the user hasn't supplied one."""
    config_path = home_path / "config.yaml"
    if config_path.exists():
        logging.info("Found existing config.yaml at %s", config_path)
        return config_path

    config_path.write_text(_CONFIG_TEMPLATE, encoding="utf-8")
    logging.info("Seeded default config.yaml at %s", config_path)
    return config_path


def _install_router_shim() -> None:
    """Replace agent.smart_model_routing.resolve_turn_route with our Smart Router.

    This must happen BEFORE gateway starts handling messages. gateway/run.py:971
    performs the import lazily inside ``_resolve_turn_agent_config`` so a
    module-attribute swap is sufficient — no need for sys.modules trickery.
    """
    # Ensure the package root is on sys.path so `import agent.smart_model_routing`
    # works when this module is invoked via `python -m custom.entry` from /app.
    here = Path(__file__).resolve().parent.parent
    if str(here) not in sys.path:
        sys.path.insert(0, str(here))

    from custom.router_adapter import install_shim
    install_shim()


def _preflight_env() -> None:
    """Validate critical env vars. Fail fast with actionable errors."""
    missing: list[str] = []
    for key in ("SLACK_BOT_TOKEN", "SLACK_APP_TOKEN", "OPENROUTER_API_KEY"):
        if not os.environ.get(key):
            missing.append(key)
    if missing:
        logging.error(
            "Missing required env vars: %s. "
            "SLACK_BOT_TOKEN (xoxb-), SLACK_APP_TOKEN (xapp-, Socket Mode), "
            "OPENROUTER_API_KEY must be set.",
            ", ".join(missing),
        )
        # Do not hard-exit — let gateway surface the platform-specific error.


async def _run_gateway() -> None:
    """Import and run the Hermes gateway."""
    from gateway.config import load_gateway_config
    from gateway.run import start_gateway

    config = load_gateway_config()
    await start_gateway(config)


def main() -> int:
    _setup_logging()
    home_path = _ensure_hermes_home()
    _seed_config_if_missing(home_path)
    _install_router_shim()
    _preflight_env()

    logging.info("Starting Hermes gateway…")
    try:
        asyncio.run(_run_gateway())
    except KeyboardInterrupt:
        logging.info("Gateway stopped by KeyboardInterrupt")
        return 0
    except Exception:
        logging.exception("Gateway crashed")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
